### ISSUE TITLE
Default hosts file goo causes problems

### ISSUE THREAD

**Issue by rakker91** [shayne/go-wsl2-host#19]
The default hosts file has a bunch of comments at the top.  If these are still present, wsl2hosts will puke.

`PS C:\wsl2host> ./wsl2host debug
wsl2host.info(1): starting wsl2host service
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/shayne/go-wsl2-host/pkg/hostsapi.parseHostfileLine(0x15, 0x646fc9, 0x1, 0xcc8, 0x646fc9, 0x1, 0x57fe60, 0xc00005e6e0)
        C:/Users/Shayne/Code/go-wsl2-host/pkg/hostsapi/hostsapi.go:35 +0x6bd
github.com/shayne/go-wsl2-host/pkg/hostsapi.(*HostsAPI).loadAndParse(0xc00012bdd0, 0xc00012bdd0, 0x0)
        C:/Users/Shayne/Code/go-wsl2-host/pkg/hostsapi/hostsapi.go:81 +0x120
github.com/shayne/go-wsl2-host/pkg/hostsapi.CreateAPI(0x554979, 0x9, 0x1, 0x0, 0x0)
        C:/Users/Shayne/Code/go-wsl2-host/pkg/hostsapi/hostsapi.go:112 +0x16c
github.com/shayne/go-wsl2-host/cmd/wsl2host/pkg/service.Run(0x581560, 0xc00005e570, 0x2, 0x0)
        C:/Users/Shayne/Code/go-wsl2-host/cmd/wsl2host/pkg/service/service.go:36 +0x1bb
github.com/shayne/go-wsl2-host/cmd/wsl2host/internal.(*windowserver).Execute(0x688b80, 0xc00005e590, 0x1, 0x1, 0xc000014240, 0xc0000142a0, 0xc0000125c0)
        C:/Users/Shayne/Code/go-wsl2-host/cmd/wsl2host/internal/service.go:33 +0x523
golang.org/x/sys/windows/svc/debug.Run(0x5545ff, 0x8, 0x57fea0, 0x688b80, 0x0, 0x0)
        C:/Users/Shayne/Code/go-wsl2-host/vendor/golang.org/x/sys/windows/svc/debug/service.go:40 +0x153
github.com/shayne/go-wsl2-host/cmd/wsl2host/internal.RunService(0x5545ff, 0x8, 0xc000010001)
        C:/Users/Shayne/Code/go-wsl2-host/cmd/wsl2host/internal/service.go:81 +0x1bf
main.main()
        C:/Users/Shayne/Code/go-wsl2-host/cmd/wsl2host/main.go:42 +0x384`

If you remove the goo at the top, it works.

Unfortunately, I've removed the goo at the top, so I can't tell you what it is anymore. :)

**Comment by robertoandrade** [comment]
I'm experiencing the same issue and gonna try this solution. The default contents on the hosts file are:

```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#       127.0.0.1       localhost
#       ::1             localhost
# Added by Docker Desktop
10.0.0.4 host.docker.internal
10.0.0.4 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

Then after a while I start seeing the normal lines added by WSL2 Hosts become lots and lots of:

```
# End of section
 xxx    # alias: Ubuntu; managed by wsl2-host
 yyy    # alias: Ubuntu; managed by wsl2-host
 zzz    # alias: Ubuntu; managed by wsl2-host
 wsl.local    # alias: Ubuntu; managed by wsl2-host
 wsl.local    # alias: Ubuntu; managed by wsl2-host
 xxx    # alias: Ubuntu; managed by wsl2-host
 yyy    # alias: Ubuntu; managed by wsl2-host
 zzz    # alias: Ubuntu; managed by wsl2-host
 xxx    # alias: Ubuntu; managed by wsl2-host
 yyy    # alias: Ubuntu; managed by wsl2-host
 zzz    # alias: Ubuntu; managed by wsl2-host
 wsl.local    # alias: Ubuntu; managed by wsl2-host
 zzz    # alias: Ubuntu; managed by wsl2-host
 wsl.local    # alias: Ubuntu; managed by wsl2-host
 xxx    # alias: Ubuntu; managed by wsl2-host
...
 zzz    # alias: Ubuntu; managed by wsl2-host
 wsl.local    # alias: Ubuntu; managed by wsl2-host
172.25.173.133 ubuntu.wsl    # managed by wsl2-host
```

And resolution stops working of course for those aliases, but the last `ubuntu.wsl`.

**Comment by Kwaadpepper** [comment]
Happened to me also, hosts parse is a bit weak I guess
