### ISSUE TITLE
Service crashes on startup

### ISSUE THREAD

**Issue by jbellmore** [shayne/go-wsl2-host#21]
Hello,

First just want to say that this utility is a real hidden gem in the world of WSL, thanks for your work! I have gotten this successfully setup and installed on 2 pc's so far but I am running into an issue with a third. It seems that the service is crashing on startup. The only real differences I can see between this computer and the other 2 is that:

- I am using docker for windows with the new WSL integration instead of having docker engine installed directly in the WSL2 environment.
- I exported the Ubuntu WSL instance from my other pc and imported it into this one. WSL is working fine so far, though I did have to configure the default user using the wsl exe as it would start as root until I did that.

Here is the output of running wsl2host debug:

```
wsl2host.info(1): starting wsl2host service
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x50bd42]

goroutine 1 [running]:
github.com/shayne/go-wsl2-host/cmd/wsl2host/pkg/service.Run(0x581560, 0xc00003a570, 0x2, 0x0)
        C:/Users/Shayne/Code/go-wsl2-host/cmd/wsl2host/pkg/service/service.go:87 +0x6b2
github.com/shayne/go-wsl2-host/cmd/wsl2host/internal.(*windowserver).Execute(0x688b80, 0xc00003a590, 0x1, 0x1, 0xc000048120, 0xc000048180, 0xc00000c4e0)
        C:/Users/Shayne/Code/go-wsl2-host/cmd/wsl2host/internal/service.go:33 +0x523
golang.org/x/sys/windows/svc/debug.Run(0x5545ff, 0x8, 0x57fea0, 0x688b80, 0x0, 0x0)
        C:/Users/Shayne/Code/go-wsl2-host/vendor/golang.org/x/sys/windows/svc/debug/service.go:40 +0x153
github.com/shayne/go-wsl2-host/cmd/wsl2host/internal.RunService(0x5545ff, 0x8, 0xc00000a001)
        C:/Users/Shayne/Code/go-wsl2-host/cmd/wsl2host/internal/service.go:81 +0x1bf
main.main()
        C:/Users/Shayne/Code/go-wsl2-host/cmd/wsl2host/main.go:42 +0x384
```

Let me know if there is any other information that may be useful.

Thanks!

**Comment by jbellmore** [comment]
After playing around with this some more it seems that since I installed docker desktop after I imported my Ubuntu distro in WSL the docker desktop wsl distro was set as the default.

Once I changed that back to Ubuntu it is working!

I will mark this as closed now.
