### ISSUE TITLE
no host add to hosts

### ISSUE THREAD

**Issue by Andreby42** [shayne/go-wsl2-host#22]
when I use admin role to install wsl2-host 

in windows registry list  it started , but then it stoped , and i check the hosts , there is no new host add to the hosts file ,then I restart the service manually , there is nothing happend to my hosts file.

I check the local security group , it's well as the wiki ,

then I run wsl2host.exe debug , I got the log

```
G:\DEV>wsl2host.exe debug
wsl2host.info(1): starting wsl2host service
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/shayne/go-wsl2-host/pkg/hostsapi.parseHostfileLine(0x24, 0x646fe0, 0x1, 0xac0, 0x646fe0, 0x1, 0x57fe60, 0xc0000862c0)
        C:/Users/Shayne/Code/go-wsl2-host/pkg/hostsapi/hostsapi.go:35 +0x6bd
github.com/shayne/go-wsl2-host/pkg/hostsapi.(*HostsAPI).loadAndParse(0xc000088300, 0xc000088300, 0x0)
        C:/Users/Shayne/Code/go-wsl2-host/pkg/hostsapi/hostsapi.go:81 +0x120
github.com/shayne/go-wsl2-host/pkg/hostsapi.CreateAPI(0x554979, 0x9, 0x4, 0x0, 0x0)
        C:/Users/Shayne/Code/go-wsl2-host/pkg/hostsapi/hostsapi.go:112 +0x16c
github.com/shayne/go-wsl2-host/cmd/wsl2host/pkg/service.Run(0x581560, 0xc00003c570, 0x2, 0x0)
        C:/Users/Shayne/Code/go-wsl2-host/cmd/wsl2host/pkg/service/service.go:36 +0x1bb
github.com/shayne/go-wsl2-host/cmd/wsl2host/internal.(*windowserver).Execute(0x688b80, 0xc00003c590, 0x1, 0x1, 0xc00004c120, 0xc00004c180, 0xc00000a580)
        C:/Users/Shayne/Code/go-wsl2-host/cmd/wsl2host/internal/service.go:33 +0x523
golang.org/x/sys/windows/svc/debug.Run(0x5545ff, 0x8, 0x57fea0, 0x688b80, 0x0, 0x0)
        C:/Users/Shayne/Code/go-wsl2-host/vendor/golang.org/x/sys/windows/svc/debug/service.go:40 +0x153
github.com/shayne/go-wsl2-host/cmd/wsl2host/internal.RunService(0x5545ff, 0x8, 0xc00000c001)
        C:/Users/Shayne/Code/go-wsl2-host/cmd/wsl2host/internal/service.go:81 +0x1bf
main.main()
        C:/Users/Shayne/Code/go-wsl2-host/cmd/wsl2host/main.go:42 +0x384
```

**Comment by Andreby42** [comment]
sovled.  I watched the hostapi code , then I change my hosts, some lines in my hosts is blanks, and in the head of the hosts file it begin with annotationes, is this   a bug , should be optimize?

**Comment by nickescobedo** [comment]
Thank you @VINO42 I had a line that had a space in it. I think that's what caused it for me.
